### ISSUE TITLE
Go to Products and All Projects Button Both Navigate to the Homepage

### ISSUE THREAD

**Issue by MarioneDev** [migsruelos/CSSWENG-GROUP-4#6]
**Summary**: 
The "Go to Products" and "All Projects" buttons in the homepage
 both navigate to the homepage and not to their supposed pages.
**Steps to Reproduce:**
-Go to Homepage 
-Click on either "Go to Products" or "All Projects" 
**Expected Results:**
-Both buttons navigate to their respective pages
**Actual Results:**
-Both buttons navigate to the homepage 
**Recommendation**
-Change the button navigation to their respective correct pages 

| Info  | Value |
| ------------- | ------------- |
| Browser  | Microsoft Edge |
| Screen Size  | 1920x1080 |
| Zoom  | 100% |

![image](https://user-images.githubusercontent.com/77104665/130922432-480bef68-cd12-4a21-b69a-2ab5c64c1e94.png)

***Clicking on either buttons navigates to homepage:***

![image](https://user-images.githubusercontent.com/77104665/130922546-612f8277-4177-47d8-8741-b26a49ef1449.png)

**Comment by miguelflores-0906** [comment]
fixed it, both should go to the products page now
